name: Aggregate WoW Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6h

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: List remote branches
        id: list
        run: |
          git fetch --all
          echo "::set-output name=branches::$( \
            git branch -r \
              | grep -E '^  origin/' \
              | sed 's#  origin/##' \
              | grep -v '^main$' \
              | tr '\n' ' ' \
          )"

      - name: Incremental aggregate per branch
        run: |
          # ensure we start from a clean slate of aggregates
          rm -rf data/aggregated
          mkdir -p data/aggregated

          for br in ${{ steps.list.outputs.branches }}; do
            echo ">>> Processing realm‑branch: $br"
            git checkout -f "$br"
            git clean -fdx   # remove any untracked leftovers

            python backend_scripts/aggregateData.py \
              --data-dir data \
              --output-dir data/aggregated \
              --incremental
          done

      - name: Commit & push aggregates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/aggregated
          if git diff --cached --quiet; then
            echo "No changes in aggregated data"
            exit 0
          fi
          git commit -m "ci: updated M+ aggregates"
          git push
