name: Aggregate WoW Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every 6 hours

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all remote branches
        run: |
          git fetch --all

      - name: Create worktrees for every branch
        run: |
          mkdir worktrees
          # for each remote branch except main, create a worktree
          git for-each-ref --format='%(refname:short)' refs/remotes/origin \
            | grep -v '^origin/main$' \
            | sed 's|^origin/||' \
            | while read br; do
                git worktree add worktrees/$br $br
              done

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Run aggregation
        run: |
          python backend_scripts/aggregateData.py \
            --branches-dir worktrees \
            --output-dir data/aggregated

      - name: Commit & push aggregates
        run: |
          set -e  # Exit script on any command failure
      
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config pull.rebase true  # Rebase
      
          git add data/aggregated
          
          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "automated: update per-dungeon aggregates"
          else
            git commit -m "Updated Leaderboard data"
          fi
      
          # Pull latest changes, fail only on actual errors
          if ! git pull --rebase; then
            echo "Error during git pull" >&2
            exit 1
          fi
      
          # Push changes, fail if there's an actual error
          if ! git push; then
            echo "Error during git push" >&2
            exit 1
          fi
