name: Move & Flatten Data to Season Layout

on:
  workflow_dispatch:
    inputs:
      season:
        description: 'Season number to assign (e.g., 14)'
        required: true
        default: '14'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - name: Move & flatten data directories in each realm branch
        env:
          SEASON: ${{ github.event.inputs.season }}
        run: |
          set -euo pipefail
          echo "Migrating only season $SEASON data, flattening nested realms…"

          # enumerate only direct remote branches (origin/branch)
          git for-each-ref --format='%(refname:short)' refs/remotes/origin/* \
            | grep '^origin/[^/]\+$' \
            | grep -vE '^(origin/HEAD|origin/main)$' \
            | sed 's@^origin/@@' \
            | while read -r branch; do

              echo "→ Checking out $branch"
              git checkout -q --track origin/"$branch"

              # flatten nested realm folder if present
              for realm_path in data/*/*; do
                [[ "$realm_path" == data/runs* ]] && continue
                region=$(basename "$(dirname "$realm_path")")
                realm=$(basename "$realm_path")
                nested="$realm_path/$realm"
                nested_season="$nested/$SEASON"

                if [ -d "$nested_season" ]; then
                  echo "Found nested season data at $nested_season"
                  for period_dir in "$nested_season"/*; do
                    [ -d "$period_dir" ] || continue
                    period=$(basename "$period_dir")
                    target="data/${region}/${realm}/${SEASON}/${period}"
                    [ -e "$target" ] && { echo "$period already in place"; continue; }
                    echo "Moving $period_dir → $target"
                    mkdir -p "$(dirname "$target")"
                    git mv "$period_dir" "$target"
                  done
                  # cleanup empty dirs
                  [ -z "$(ls -A "$nested_season")" ] && rmdir "$nested_season"
                  if [ -d "$nested" ] && [ -z "$(ls -A "$nested")" ]; then
                    echo "Removing empty $nested"
                    rmdir "$nested"
                  fi
                  git add -u "$realm_path"
                fi
              done

              if git diff --cached --quiet; then
                echo "   ✔ No changes in $branch"
              else
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git commit -m "chore: flatten nested realm data for season ${SEASON}"
                echo "   ↪ Pushing $branch"
                git push --set-upstream origin "$branch"
              fi
            done

          git checkout main
          echo "Migration complete for season $SEASON"
