name: Cleanup WoW Data Structure

on:
  workflow_dispatch:
    inputs:
      season:
        description: 'Season number to keep (e.g., 14)'
        required: true
        default: '14'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - name: Prune and retain only correct files
        env:
          SEASON: ${{ github.event.inputs.season }}
        run: |
          set -euo pipefail
          echo "Cleaning up data structure for season $SEASON"

          # loop over every remote branch except main/HEAD
          git for-each-ref --format='%(refname:short)' refs/remotes/origin/* \
            | grep '^origin/[^/]\+$' \
            | grep -vE '^(origin/HEAD|origin/main)$' \
            | sed 's@^origin/@@' \
            | while read -r branch; do

              echo "→ Branch: $branch"
              git checkout -q --track origin/"$branch"

              # remove any file or directory under data/ that does NOT match our keep patterns
              #  keep: 
              #    data/{region}/{realm}/{SEASON}/{period}/runs.csv
              #    data/{region}/{realm}/{SEASON}/{period}/equipment/**
              #    data/{region}/{realm}/{SEASON}/{period}/specializations/**
              #
              # anything else gets git-rm -r

              # find all paths under data/
              find data -mindepth 1 | while read -r path; do
                # normalize
                rel=${path#data/}

                # check keep conditions
                if [[ "$rel" =~ ^[^/]+/[^/]+/${SEASON}/[^/]+/runs\.csv$ ]]; then
                  continue
                fi
                if [[ "$rel" =~ ^[^/]+/[^/]+/${SEASON}/[^/]+/equipment(/|$) ]]; then
                  continue
                fi
                if [[ "$rel" =~ ^[^/]+/[^/]+/${SEASON}/[^/]+/specializations(/|$) ]]; then
                  continue
                fi

                # otherwise remove
                echo "   🗑  Removing $path"
                git rm -rf --ignore-unmatch "$path"
              done

              # prune any empty dirs under data/
              find data -type d -empty -print | while read -r d; do
                echo "Rmdir $d"
                git rm -rf --ignore-unmatch "$d"
              done

              # commit & push if needed
              if git diff --cached --quiet; then
                echo "Nothing to clean on $branch"
              else
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git commit -m "chore: prune data to season ${SEASON} layout"
                git push --set-upstream origin "$branch"
              fi
            done

          # back to main
          git checkout main
          echo "Cleanup complete for season $SEASON"
